export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    generateExcuse: 'Generate Excuse',
    proofGenerator: 'Proof Generator',
    emergencyAlerts: 'Emergency Alerts',
    apologyGenerator: 'Apology Generator',
    settings: 'Settings',
    savedExcuses: 'Saved Excuses',
    
    // Common terms
    believabilityScore: 'Believability Score',
    category: 'Category',
    urgency: 'Urgency',
    audience: 'Audience',
    relationship: 'Relationship',
    generateNow: 'Generate Now',
    saveExcuse: 'Save Excuse',
    copyToClipboard: 'Copy to Clipboard',
    shareExcuse: 'Share Excuse',
    customizeProof: 'Customize Proof',
    scheduleAlert: 'Schedule Alert',
    voicePlayback: 'Voice Playback',
    
    // Categories
    work: 'Work',
    medical: 'Medical',
    family: 'Family',
    transport: 'Transport',
    technology: 'Technology',
    weather: 'Weather',
    emergency: 'Emergency',
    personal: 'Personal',
    
    // Urgency levels
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
    
    // Audience types
    workProfessional: 'Work/Professional',
    friends: 'Friends',
    romanticPartner: 'Romantic Partner',
    authorityFigure: 'Authority Figure',
    
    // Relationship types
    close: 'Close',
    professional: 'Professional',
    casual: 'Casual',
    distant: 'Distant',
    
    // Actions
    copy: 'Copy',
    save: 'Save',
    download: 'Download',
    share: 'Share',
    voice: 'Voice',
    stop: 'Stop',
    copied: 'Copied!',
    saved: 'Saved!',
    downloaded: 'Downloaded!',
    
    // Generator page
    createContextAware: 'Create context-aware, believable excuses with AI assistance',
    configureContext: 'Configure Context',
    situation: 'Situation',
    generatedExcuse: 'Generated Excuse',
    generating: 'Generating...',
    readyToGenerate: 'Ready to Generate',
    configureContextAndGenerate: 'Configure your context and click generate to create your excuse',
    
    // Share modal
    checkOutExcuse: 'Check out this excuse',
    shareLinkCopied: 'Share link copied to clipboard!',
    textCopiedInstagram: 'Text copied! Paste it in your Instagram post.',
    copyLink: 'Copy Link',
    believability: 'Believability',
    
    // Voice
    voiceNotSupported: 'Text-to-speech is not supported in your browser.',
    
    // Download content
    excuseDocument: 'EXCUSE DOCUMENT',
    generated: 'Generated',
    generatedBy: 'Generated by',
    forPersonalUse: 'This content is for personal use only.',
    
    // Context enhancement
    urgent: 'URGENT',
    requiresImmediateAttention: 'This requires immediate attention',
    quiteSerious: 'This is quite serious and can\'t be delayed',
    sincerelyApologize: 'I sincerely apologize for any inconvenience this may cause',
    reallySorry: 'I\'m really sorry about this, I know it\'s not ideal timing'
  },
  es: {
    // Navigation
    dashboard: 'Panel de Control',
    generateExcuse: 'Generar Excusa',
    proofGenerator: 'Generador de Pruebas',
    emergencyAlerts: 'Alertas de Emergencia',
    apologyGenerator: 'Generador de Disculpas',
    settings: 'Configuración',
    savedExcuses: 'Excusas Guardadas',
    
    // Common terms
    believabilityScore: 'Puntuación de Credibilidad',
    category: 'Categoría',
    urgency: 'Urgencia',
    audience: 'Audiencia',
    relationship: 'Relación',
    generateNow: 'Generar Ahora',
    saveExcuse: 'Guardar Excusa',
    copyToClipboard: 'Copiar al Portapapeles',
    shareExcuse: 'Compartir Excusa',
    customizeProof: 'Personalizar Prueba',
    scheduleAlert: 'Programar Alerta',
    voicePlayback: 'Reproducción de Voz',
    
    // Categories
    work: 'Trabajo',
    medical: 'Médico',
    family: 'Familia',
    transport: 'Transporte',
    technology: 'Tecnología',
    weather: 'Clima',
    emergency: 'Emergencia',
    personal: 'Personal',
    
    // Urgency levels
    low: 'Bajo',
    medium: 'Medio',
    high: 'Alto',
    critical: 'Crítico',
    
    // Audience types
    workProfessional: 'Trabajo/Profesional',
    friends: 'Amigos',
    romanticPartner: 'Pareja Romántica',
    authorityFigure: 'Figura de Autoridad',
    
    // Relationship types
    close: 'Cercano',
    professional: 'Profesional',
    casual: 'Casual',
    distant: 'Distante',
    
    // Actions
    copy: 'Copiar',
    save: 'Guardar',
    download: 'Descargar',
    share: 'Compartir',
    voice: 'Voz',
    stop: 'Parar',
    copied: '¡Copiado!',
    saved: '¡Guardado!',
    downloaded: '¡Descargado!',
    
    // Generator page
    createContextAware: 'Crear excusas creíbles y conscientes del contexto con asistencia de IA',
    configureContext: 'Configurar Contexto',
    situation: 'Situación',
    generatedExcuse: 'Excusa Generada',
    generating: 'Generando...',
    readyToGenerate: 'Listo para Generar',
    configureContextAndGenerate: 'Configura tu contexto y haz clic en generar para crear tu excusa',
    
    // Share modal
    checkOutExcuse: 'Mira esta excusa',
    shareLinkCopied: '¡Enlace compartido copiado al portapapeles!',
    textCopiedInstagram: '¡Texto copiado! Pégalo en tu publicación de Instagram.',
    copyLink: 'Copiar Enlace',
    believability: 'Credibilidad',
    
    // Voice
    voiceNotSupported: 'La síntesis de voz no es compatible con tu navegador.',
    
    // Download content
    excuseDocument: 'DOCUMENTO DE EXCUSA',
    generated: 'Generado',
    generatedBy: 'Generado por',
    forPersonalUse: 'Este contenido es solo para uso personal.',
    
    // Context enhancement
    urgent: 'URGENTE',
    requiresImmediateAttention: 'Esto requiere atención inmediata',
    quiteSerious: 'Esto es bastante serio y no puede retrasarse',
    sincerelyApologize: 'Me disculpo sinceramente por cualquier inconveniente que esto pueda causar',
    reallySorry: 'Lo siento mucho por esto, sé que no es el momento ideal'
  },
  fr: {
    // Navigation
    dashboard: 'Tableau de Bord',
    generateExcuse: 'Générer une Excuse',
    proofGenerator: 'Générateur de Preuves',
    emergencyAlerts: 'Alertes d\'Urgence',
    apologyGenerator: 'Générateur d\'Excuses',
    settings: 'Paramètres',
    savedExcuses: 'Excuses Sauvegardées',
    
    // Common terms
    believabilityScore: 'Score de Crédibilité',
    category: 'Catégorie',
    urgency: 'Urgence',
    audience: 'Public',
    relationship: 'Relation',
    generateNow: 'Générer Maintenant',
    saveExcuse: 'Sauvegarder l\'Excuse',
    copyToClipboard: 'Copier dans le Presse-papiers',
    shareExcuse: 'Partager l\'Excuse',
    customizeProof: 'Personnaliser la Preuve',
    scheduleAlert: 'Programmer une Alerte',
    voicePlayback: 'Lecture Vocale',
    
    // Categories
    work: 'Travail',
    medical: 'Médical',
    family: 'Famille',
    transport: 'Transport',
    technology: 'Technologie',
    weather: 'Météo',
    emergency: 'Urgence',
    personal: 'Personnel',
    
    // Urgency levels
    low: 'Faible',
    medium: 'Moyen',
    high: 'Élevé',
    critical: 'Critique',
    
    // Audience types
    workProfessional: 'Travail/Professionnel',
    friends: 'Amis',
    romanticPartner: 'Partenaire Romantique',
    authorityFigure: 'Figure d\'Autorité',
    
    // Relationship types
    close: 'Proche',
    professional: 'Professionnel',
    casual: 'Décontracté',
    distant: 'Distant',
    
    // Actions
    copy: 'Copier',
    save: 'Sauvegarder',
    download: 'Télécharger',
    share: 'Partager',
    voice: 'Voix',
    stop: 'Arrêter',
    copied: 'Copié!',
    saved: 'Sauvegardé!',
    downloaded: 'Téléchargé!',
    
    // Generator page
    createContextAware: 'Créer des excuses crédibles et contextuelles avec l\'assistance IA',
    configureContext: 'Configurer le Contexte',
    situation: 'Situation',
    generatedExcuse: 'Excuse Générée',
    generating: 'Génération...',
    readyToGenerate: 'Prêt à Générer',
    configureContextAndGenerate: 'Configurez votre contexte et cliquez sur générer pour créer votre excuse',
    
    // Share modal
    checkOutExcuse: 'Découvrez cette excuse',
    shareLinkCopied: 'Lien de partage copié dans le presse-papiers!',
    textCopiedInstagram: 'Texte copié! Collez-le dans votre publication Instagram.',
    copyLink: 'Copier le Lien',
    believability: 'Crédibilité',
    
    // Voice
    voiceNotSupported: 'La synthèse vocale n\'est pas prise en charge par votre navigateur.',
    
    // Download content
    excuseDocument: 'DOCUMENT D\'EXCUSE',
    generated: 'Généré',
    generatedBy: 'Généré par',
    forPersonalUse: 'Ce contenu est uniquement à usage personnel.',
    
    // Context enhancement
    urgent: 'URGENT',
    requiresImmediateAttention: 'Ceci nécessite une attention immédiate',
    quiteSerious: 'C\'est assez sérieux et ne peut pas être retardé',
    sincerelyApologize: 'Je m\'excuse sincèrement pour tout inconvénient que cela pourrait causer',
    reallySorry: 'Je suis vraiment désolé pour cela, je sais que ce n\'est pas le moment idéal'
  },
  hi: {
    // Navigation
    dashboard: 'डैशबोर्ड',
    generateExcuse: 'बहाना बनाएं',
    proofGenerator: 'प्रमाण जेनरेटर',
    emergencyAlerts: 'आपातकालीन अलर्ट',
    apologyGenerator: 'माफी जेनरेटर',
    settings: 'सेटिंग्स',
    savedExcuses: 'सहेजे गए बहाने',
    
    // Common terms
    believabilityScore: 'विश्वसनीयता स्कोर',
    category: 'श्रेणी',
    urgency: 'तात्कालिकता',
    audience: 'दर्शक',
    relationship: 'रिश्ता',
    generateNow: 'अभी बनाएं',
    saveExcuse: 'बहाना सहेजें',
    copyToClipboard: 'क्लिपबोर्ड पर कॉपी करें',
    shareExcuse: 'बहाना साझा करें',
    customizeProof: 'प्रमाण कस्टमाइज़ करें',
    scheduleAlert: 'अलर्ट शेड्यूल करें',
    voicePlayback: 'आवाज़ प्लेबैक',
    
    // Categories
    work: 'काम',
    medical: 'चिकित्सा',
    family: 'परिवार',
    transport: 'परिवहन',
    technology: 'तकनीक',
    weather: 'मौसम',
    emergency: 'आपातकाल',
    personal: 'व्यक्तिगत',
    
    // Urgency levels
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    critical: 'गंभीर',
    
    // Audience types
    workProfessional: 'काम/पेशेवर',
    friends: 'दोस्त',
    romanticPartner: 'रोमांटिक पार्टनर',
    authorityFigure: 'अधिकारी व्यक्ति',
    
    // Relationship types
    close: 'करीबी',
    professional: 'पेशेवर',
    casual: 'आकस्मिक',
    distant: 'दूर',
    
    // Actions
    copy: 'कॉपी',
    save: 'सहेजें',
    download: 'डाउनलोड',
    share: 'साझा करें',
    voice: 'आवाज़',
    stop: 'रोकें',
    copied: 'कॉपी हो गया!',
    saved: 'सहेज लिया!',
    downloaded: 'डाउनलोड हो गया!',
    
    // Generator page
    createContextAware: 'AI सहायता के साथ संदर्भ-जागरूक, विश्वसनीय बहाने बनाएं',
    configureContext: 'संदर्भ कॉन्फ़िगर करें',
    situation: 'स्थिति',
    generatedExcuse: 'उत्पन्न बहाना',
    generating: 'उत्पन्न कर रहे हैं...',
    readyToGenerate: 'उत्पन्न करने के लिए तैयार',
    configureContextAndGenerate: 'अपना संदर्भ कॉन्फ़िगर करें और अपना बहाना बनाने के लिए जेनरेट पर क्लिक करें',
    
    // Share modal
    checkOutExcuse: 'इस बहाने को देखें',
    shareLinkCopied: 'शेयर लिंक क्लिपबोर्ड पर कॉपी हो गया!',
    textCopiedInstagram: 'टेक्स्ट कॉपी हो गया! इसे अपनी Instagram पोस्ट में पेस्ट करें।',
    copyLink: 'लिंक कॉपी करें',
    believability: 'विश्वसनीयता',
    
    // Voice
    voiceNotSupported: 'आपके ब्राउज़र में टेक्स्ट-टू-स्पीच समर्थित नहीं है।',
    
    // Download content
    excuseDocument: 'बहाना दस्तावेज़',
    generated: 'उत्पन्न',
    generatedBy: 'द्वारा उत्पन्न',
    forPersonalUse: 'यह सामग्री केवल व्यक्तिगत उपयोग के लिए है।',
    
    // Context enhancement
    urgent: 'तत्काल',
    requiresImmediateAttention: 'इसमें तत्काल ध्यान देने की आवश्यकता है',
    quiteSerious: 'यह काफी गंभीर है और देरी नहीं की जा सकती',
    sincerelyApologize: 'इससे होने वाली किसी भी असुविधा के लिए मैं ईमानदारी से माफी मांगता हूं',
    reallySorry: 'मुझे इसके लिए वास्तव में खुशी है, मुझे पता है कि यह आदर्श समय नहीं है'
  },
  ml: {
    // Navigation
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    generateExcuse: 'ഒഴികഴിവ് സൃഷ്ടിക്കുക',
    proofGenerator: 'പ്രൂഫ് ജനറേറ്റർ',
    emergencyAlerts: 'അടിയന്തര അലേർട്ടുകൾ',
    apologyGenerator: 'ക്ഷമാപണ ജനറേറ്റർ',
    settings: 'ക്രമീകരണങ്ങൾ',
    savedExcuses: 'സംരക്ഷിച്ച ഒഴികഴിവുകൾ',
    
    // Common terms
    believabilityScore: 'വിശ്വസനീയത സ്കോർ',
    category: 'വിഭാഗം',
    urgency: 'അടിയന്തിരത',
    audience: 'പ്രേക്ഷകർ',
    relationship: 'ബന്ധം',
    generateNow: 'ഇപ്പോൾ സൃഷ്ടിക്കുക',
    saveExcuse: 'ഒഴികഴിവ് സംരക്ഷിക്കുക',
    copyToClipboard: 'ക്ലിപ്പ്ബോർഡിലേക്ക് പകർത്തുക',
    shareExcuse: 'ഒഴികഴിവ് പങ്കിടുക',
    customizeProof: 'പ്രൂഫ് കസ്റ്റമൈസ് ചെയ്യുക',
    scheduleAlert: 'അലേർട്ട് ഷെഡ്യൂൾ ചെയ്യുക',
    voicePlayback: 'വോയ്സ് പ്ലേബാക്ക്',
    
    // Categories
    work: 'ജോലി',
    medical: 'മെഡിക്കൽ',
    family: 'കുടുംബം',
    transport: 'ഗതാഗതം',
    technology: 'സാങ്കേതികവിദ്യ',
    weather: 'കാലാവസ്ഥ',
    emergency: 'അടിയന്തിരാവസ്ഥ',
    personal: 'വ്യക്തിഗത',
    
    // Urgency levels
    low: 'കുറഞ്ഞ',
    medium: 'ഇടത്തരം',
    high: 'ഉയർന്ന',
    critical: 'ഗുരുതരമായ',
    
    // Audience types
    workProfessional: 'ജോലി/പ്രൊഫഷണൽ',
    friends: 'സുഹൃത്തുക്കൾ',
    romanticPartner: 'റൊമാന്റിക് പാർട്ണർ',
    authorityFigure: 'അധികാര വ്യക്തി',
    
    // Relationship types
    close: 'അടുത്ത',
    professional: 'പ്രൊഫഷണൽ',
    casual: 'സാധാരണ',
    distant: 'അകലെയുള്ള',
    
    // Actions
    copy: 'പകർത്തുക',
    save: 'സംരക്ഷിക്കുക',
    download: 'ഡൗൺലോഡ്',
    share: 'പങ്കിടുക',
    voice: 'ശബ്ദം',
    stop: 'നിർത്തുക',
    copied: 'പകർത്തി!',
    saved: 'സംരക്ഷിച്ചു!',
    downloaded: 'ഡൗൺലോഡ് ചെയ്തു!',
    
    // Generator page
    createContextAware: 'AI സഹായത്തോടെ സന്ദർഭ-ബോധമുള്ള, വിശ്വസനീയമായ ഒഴികഴിവുകൾ സൃഷ്ടിക്കുക',
    configureContext: 'സന്ദർഭം കോൺഫിഗർ ചെയ്യുക',
    situation: 'സാഹചര്യം',
    generatedExcuse: 'സൃഷ്ടിച്ച ഒഴികഴിവ്',
    generating: 'സൃഷ്ടിക്കുന്നു...',
    readyToGenerate: 'സൃഷ്ടിക്കാൻ തയ്യാർ',
    configureContextAndGenerate: 'നിങ്ങളുടെ സന്ദർഭം കോൺഫിഗർ ചെയ്ത് നിങ്ങളുടെ ഒഴികഴിവ് സൃഷ്ടിക്കാൻ ജനറേറ്റിൽ ക്ലിക്ക് ചെയ്യുക',
    
    // Share modal
    checkOutExcuse: 'ഈ ഒഴികഴിവ് പരിശോധിക്കുക',
    shareLinkCopied: 'ഷെയർ ലിങ്ക് ക്ലിപ്പ്ബോർഡിലേക്ക് പകർത്തി!',
    textCopiedInstagram: 'ടെക്സ്റ്റ് പകർത്തി! നിങ്ങളുടെ Instagram പോസ്റ്റിൽ ഒട്ടിക്കുക.',
    copyLink: 'ലിങ്ക് പകർത്തുക',
    believability: 'വിശ്വസനീയത',
    
    // Voice
    voiceNotSupported: 'നിങ്ങളുടെ ബ്രൗസറിൽ ടെക്സ്റ്റ്-ടു-സ്പീച്ച് പിന്തുണയ്ക്കുന്നില്ല.',
    
    // Download content
    excuseDocument: 'ഒഴികഴിവ് രേഖ',
    generated: 'സൃഷ്ടിച്ചത്',
    generatedBy: 'സൃഷ്ടിച്ചത്',
    forPersonalUse: 'ഈ ഉള്ളടക്കം വ്യക്തിഗത ഉപയോഗത്തിന് മാത്രമാണ്.',
    
    // Context enhancement
    urgent: 'അടിയന്തിരം',
    requiresImmediateAttention: 'ഇതിന് ഉടനടി ശ്രദ്ധ ആവശ്യമാണ്',
    quiteSerious: 'ഇത് വളരെ ഗുരുതരമാണ്, കാലതാമസം വരുത്താൻ കഴിയില്ല',
    sincerelyApologize: 'ഇത് കാരണമായേക്കാവുന്ന ഏതെങ്കിലും അസൗകര്യത്തിന് ഞാൻ ആത്മാർത്ഥമായി ക്ഷമ ചോദിക്കുന്നു',
    reallySorry: 'ഇതിനെക്കുറിച്ച് ഞാൻ ശരിക്കും ഖേദിക്കുന്നു, ഇത് അനുയോജ്യമായ സമയമല്ലെന്ന് എനിക്കറിയാം'
  },
  te: {
    // Navigation
    dashboard: 'డాష్‌బోర్డ్',
    generateExcuse: 'సాకు సృష్టించండి',
    proofGenerator: 'ప్రూఫ్ జనరేటర్',
    emergencyAlerts: 'అత్యవసర హెచ్చరికలు',
    apologyGenerator: 'క్షమాపణ జనరేటర్',
    settings: 'సెట్టింగులు',
    savedExcuses: 'సేవ్ చేసిన సాకులు',
    
    // Common terms
    believabilityScore: 'నమ్మకత్వ స్కోర్',
    category: 'వర్గం',
    urgency: 'అత్యవసరత',
    audience: 'ప్రేక్షకులు',
    relationship: 'సంబంధం',
    generateNow: 'ఇప్పుడు సృష్టించండి',
    saveExcuse: 'సాకు సేవ్ చేయండి',
    copyToClipboard: 'క్లిప్‌బోర్డ్‌కు కాపీ చేయండి',
    shareExcuse: 'సాకు షేర్ చేయండి',
    customizeProof: 'ప్రూఫ్ కస్టమైజ్ చేయండి',
    scheduleAlert: 'అలర్ట్ షెడ్యూల్ చేయండి',
    voicePlayback: 'వాయిస్ ప్లేబ్యాక్',
    
    // Categories
    work: 'పని',
    medical: 'వైద్య',
    family: 'కుటుంబం',
    transport: 'రవాణా',
    technology: 'సాంకేతికత',
    weather: 'వాతావరణం',
    emergency: 'అత్యవసర',
    personal: 'వ్యక్తిగత',
    
    // Urgency levels
    low: 'తక్కువ',
    medium: 'మధ్యస్థ',
    high: 'అధిక',
    critical: 'క్లిష్టమైన',
    
    // Audience types
    workProfessional: 'పని/వృత్తిపరమైన',
    friends: 'స్నేహితులు',
    romanticPartner: 'రొమాంటిక్ పార్టనర్',
    authorityFigure: 'అధికార వ్యక్తి',
    
    // Relationship types
    close: 'దగ్గరి',
    professional: 'వృత్తిపరమైన',
    casual: 'సాధారణ',
    distant: 'దూరపు',
    
    // Actions
    copy: 'కాపీ',
    save: 'సేవ్',
    download: 'డౌన్‌లోడ్',
    share: 'షేర్',
    voice: 'వాయిస్',
    stop: 'ఆపండి',
    copied: 'కాపీ అయింది!',
    saved: 'సేవ్ అయింది!',
    downloaded: 'డౌన్‌లోడ్ అయింది!',
    
    // Generator page
    createContextAware: 'AI సహాయంతో సందర్భ-అవగాహనతో కూడిన, నమ్మదగిన సాకులను సృష్టించండి',
    configureContext: 'సందర్భాన్ని కాన్ఫిగర్ చేయండి',
    situation: 'పరిస్థితి',
    generatedExcuse: 'సృష్టించిన సాకు',
    generating: 'సృష్టిస్తోంది...',
    readyToGenerate: 'సృష్టించడానికి సిద్ధం',
    configureContextAndGenerate: 'మీ సందర్భాన్ని కాన్ఫిగర్ చేసి మీ సాకును సృష్టించడానికి జనరేట్‌పై క్లిక్ చేయండి',
    
    // Share modal
    checkOutExcuse: 'ఈ సాకును చూడండి',
    shareLinkCopied: 'షేర్ లింక్ క్లిప్‌బోర్డ్‌కు కాపీ అయింది!',
    textCopiedInstagram: 'టెక్స్ట్ కాపీ అయింది! మీ Instagram పోస్ట్‌లో పేస్ట్ చేయండి.',
    copyLink: 'లింక్ కాపీ చేయండి',
    believability: 'నమ్మకత్వం',
    
    // Voice
    voiceNotSupported: 'మీ బ్రౌజర్‌లో టెక్స్ట్-టు-స్పీచ్ మద్దతు లేదు.',
    
    // Download content
    excuseDocument: 'సాకు పత్రం',
    generated: 'సృష్టించబడింది',
    generatedBy: 'సృష్టించినది',
    forPersonalUse: 'ఈ కంటెంట్ వ్యక్తిగత వినియోగం కోసం మాత్రమే.',
    
    // Context enhancement
    urgent: 'అత్యవసరం',
    requiresImmediateAttention: 'దీనికి తక్షణ దృష్టి అవసరం',
    quiteSerious: 'ఇది చాలా తీవ్రమైనది మరియు ఆలస్యం చేయలేము',
    sincerelyApologize: 'దీని వల్ల కలిగే ఏదైనా అసౌకర్యానికి నేను హృదయపూర్వకంగా క్షమాపణలు కోరుతున్నాను',
    reallySorry: 'దీని గురించి నేను నిజంగా క్షమించండి, ఇది ఆదర్శ సమయం కాదని నాకు తెలుసు'
  },
  ta: {
    // Navigation
    dashboard: 'டாஷ்போர்டு',
    generateExcuse: 'சாக்கு உருவாக்கவும்',
    proofGenerator: 'ஆதார ஜெனரேட்டர்',
    emergencyAlerts: 'அவசர எச்சரிக்கைகள்',
    apologyGenerator: 'மன்னிப்பு ஜெனரேட்டர்',
    settings: 'அமைப்புகள்',
    savedExcuses: 'சேமிக்கப்பட்ட சாக்குகள்',
    
    // Common terms
    believabilityScore: 'நம்பகத்தன்மை மதிப்பெண்',
    category: 'வகை',
    urgency: 'அவசரம்',
    audience: 'பார்வையாளர்கள்',
    relationship: 'உறவு',
    generateNow: 'இப்போது உருவாக்கவும்',
    saveExcuse: 'சாக்கு சேமிக்கவும்',
    copyToClipboard: 'கிளிப்போர்டுக்கு நகலெடுக்கவும்',
    shareExcuse: 'சாக்கு பகிரவும்',
    customizeProof: 'ஆதாரத்தை தனிப்பயனாக்கவும்',
    scheduleAlert: 'எச்சரிக்கை திட்டமிடவும்',
    voicePlayback: 'குரல் பிளேபேக்',
    
    // Categories
    work: 'வேலை',
    medical: 'மருத்துவ',
    family: 'குடும்பம்',
    transport: 'போக்குவரத்து',
    technology: 'தொழில்நுட்பம்',
    weather: 'வானிலை',
    emergency: 'அவசரநிலை',
    personal: 'தனிப்பட்ட',
    
    // Urgency levels
    low: 'குறைவு',
    medium: 'நடுத்தர',
    high: 'உயர்',
    critical: 'முக்கியமான',
    
    // Audience types
    workProfessional: 'வேலை/தொழில்முறை',
    friends: 'நண்பர்கள்',
    romanticPartner: 'காதல் துணை',
    authorityFigure: 'அதிகார நபர்',
    
    // Relationship types
    close: 'நெருக்கமான',
    professional: 'தொழில்முறை',
    casual: 'சாதாரண',
    distant: 'தொலைவான',
    
    // Actions
    copy: 'நகலெடு',
    save: 'சேமி',
    download: 'பதிவிறக்கம்',
    share: 'பகிர்',
    voice: 'குரல்',
    stop: 'நிறுத்து',
    copied: 'நகலெடுக்கப்பட்டது!',
    saved: 'சேமிக்கப்பட்டது!',
    downloaded: 'பதிவிறக்கப்பட்டது!',
    
    // Generator page
    createContextAware: 'AI உதவியுடன் சூழல்-விழிப்புணர்வு, நம்பகமான சாக்குகளை உருவாக்கவும்',
    configureContext: 'சூழலை கட்டமைக்கவும்',
    situation: 'நிலைமை',
    generatedExcuse: 'உருவாக்கப்பட்ட சாக்கு',
    generating: 'உருவாக்குகிறது...',
    readyToGenerate: 'உருவாக்க தயார்',
    configureContextAndGenerate: 'உங்கள் சூழலை கட்டமைத்து உங்கள் சாக்கை உருவாக்க ஜெனரேட்டில் கிளிக் செய்யவும்',
    
    // Share modal
    checkOutExcuse: 'இந்த சாக்கை பார்க்கவும்',
    shareLinkCopied: 'பகிர்வு இணைப்பு கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது!',
    textCopiedInstagram: 'உரை நகலெடுக்கப்பட்டது! உங்கள் Instagram இடுகையில் ஒட்டவும்.',
    copyLink: 'இணைப்பை நகலெடுக்கவும்',
    believability: 'நம்பகத்தன்மை',
    
    // Voice
    voiceNotSupported: 'உங்கள் உலாவியில் உரை-க்கு-பேச்சு ஆதரிக்கப்படவில்லை.',
    
    // Download content
    excuseDocument: 'சாக்கு ஆவணம்',
    generated: 'உருவாக்கப்பட்டது',
    generatedBy: 'உருவாக்கியது',
    forPersonalUse: 'இந்த உள்ளடக்கம் தனிப்பட்ட பயன்பாட்டிற்கு மட்டுமே.',
    
    // Context enhancement
    urgent: 'அவசரம்',
    requiresImmediateAttention: 'இதற்கு உடனடி கவனம் தேவை',
    quiteSerious: 'இது மிகவும் தீவிரமானது மற்றும் தாமதப்படுத்த முடியாது',
    sincerelyApologize: 'இதனால் ஏற்படக்கூடிய எந்த சிரமத்திற்கும் நான் உண்மையாக மன்னிப்பு கேட்கிறேன்',
    reallySorry: 'இதற்காக நான் மிகவும் வருந்துகிறேன், இது சரியான நேரம் அல்ல என்று எனக்குத் தெரியும்'
  },
  de: {
    // Navigation
    dashboard: 'Dashboard',
    generateExcuse: 'Ausrede Generieren',
    proofGenerator: 'Beweis Generator',
    emergencyAlerts: 'Notfall Alarme',
    apologyGenerator: 'Entschuldigung Generator',
    settings: 'Einstellungen',
    savedExcuses: 'Gespeicherte Ausreden',
    
    // Common terms
    believabilityScore: 'Glaubwürdigkeits-Score',
    category: 'Kategorie',
    urgency: 'Dringlichkeit',
    audience: 'Publikum',
    relationship: 'Beziehung',
    generateNow: 'Jetzt Generieren',
    saveExcuse: 'Ausrede Speichern',
    copyToClipboard: 'In Zwischenablage Kopieren',
    shareExcuse: 'Ausrede Teilen',
    customizeProof: 'Beweis Anpassen',
    scheduleAlert: 'Alarm Planen',
    voicePlayback: 'Sprachausgabe',
    
    // Categories
    work: 'Arbeit',
    medical: 'Medizinisch',
    family: 'Familie',
    transport: 'Transport',
    technology: 'Technologie',
    weather: 'Wetter',
    emergency: 'Notfall',
    personal: 'Persönlich',
    
    // Urgency levels
    low: 'Niedrig',
    medium: 'Mittel',
    high: 'Hoch',
    critical: 'Kritisch',
    
    // Audience types
    workProfessional: 'Arbeit/Beruflich',
    friends: 'Freunde',
    romanticPartner: 'Romantischer Partner',
    authorityFigure: 'Autoritätsperson',
    
    // Relationship types
    close: 'Nah',
    professional: 'Beruflich',
    casual: 'Locker',
    distant: 'Distanziert',
    
    // Actions
    copy: 'Kopieren',
    save: 'Speichern',
    download: 'Herunterladen',
    share: 'Teilen',
    voice: 'Stimme',
    stop: 'Stoppen',
    copied: 'Kopiert!',
    saved: 'Gespeichert!',
    downloaded: 'Heruntergeladen!',
    
    // Generator page
    createContextAware: 'Erstellen Sie kontextbewusste, glaubwürdige Ausreden mit KI-Unterstützung',
    configureContext: 'Kontext Konfigurieren',
    situation: 'Situation',
    generatedExcuse: 'Generierte Ausrede',
    generating: 'Generiere...',
    readyToGenerate: 'Bereit zum Generieren',
    configureContextAndGenerate: 'Konfigurieren Sie Ihren Kontext und klicken Sie auf Generieren, um Ihre Ausrede zu erstellen',
    
    // Share modal
    checkOutExcuse: 'Schauen Sie sich diese Ausrede an',
    shareLinkCopied: 'Share-Link in die Zwischenablage kopiert!',
    textCopiedInstagram: 'Text kopiert! Fügen Sie ihn in Ihren Instagram-Post ein.',
    copyLink: 'Link Kopieren',
    believability: 'Glaubwürdigkeit',
    
    // Voice
    voiceNotSupported: 'Text-zu-Sprache wird in Ihrem Browser nicht unterstützt.',
    
    // Download content
    excuseDocument: 'AUSREDEN-DOKUMENT',
    generated: 'Generiert',
    generatedBy: 'Generiert von',
    forPersonalUse: 'Dieser Inhalt ist nur für den persönlichen Gebrauch bestimmt.',
    
    // Context enhancement
    urgent: 'DRINGEND',
    requiresImmediateAttention: 'Dies erfordert sofortige Aufmerksamkeit',
    quiteSerious: 'Das ist ziemlich ernst und kann nicht verzögert werden',
    sincerelyApologize: 'Ich entschuldige mich aufrichtig für alle Unannehmlichkeiten, die dies verursachen könnte',
    reallySorry: 'Es tut mir wirklich leid, ich weiß, dass es nicht der ideale Zeitpunkt ist'
  },
  it: {
    // Navigation
    dashboard: 'Dashboard',
    generateExcuse: 'Genera Scusa',
    proofGenerator: 'Generatore di Prove',
    emergencyAlerts: 'Avvisi di Emergenza',
    apologyGenerator: 'Generatore di Scuse',
    settings: 'Impostazioni',
    savedExcuses: 'Scuse Salvate',
    
    // Common terms
    believabilityScore: 'Punteggio di Credibilità',
    category: 'Categoria',
    urgency: 'Urgenza',
    audience: 'Pubblico',
    relationship: 'Relazione',
    generateNow: 'Genera Ora',
    saveExcuse: 'Salva Scusa',
    copyToClipboard: 'Copia negli Appunti',
    shareExcuse: 'Condividi Scusa',
    customizeProof: 'Personalizza Prova',
    scheduleAlert: 'Programma Avviso',
    voicePlayback: 'Riproduzione Vocale',
    
    // Categories
    work: 'Lavoro',
    medical: 'Medico',
    family: 'Famiglia',
    transport: 'Trasporto',
    technology: 'Tecnologia',
    weather: 'Tempo',
    emergency: 'Emergenza',
    personal: 'Personale',
    
    // Urgency levels
    low: 'Basso',
    medium: 'Medio',
    high: 'Alto',
    critical: 'Critico',
    
    // Audience types
    workProfessional: 'Lavoro/Professionale',
    friends: 'Amici',
    romanticPartner: 'Partner Romantico',
    authorityFigure: 'Figura di Autorità',
    
    // Relationship types
    close: 'Stretto',
    professional: 'Professionale',
    casual: 'Casuale',
    distant: 'Distante',
    
    // Actions
    copy: 'Copia',
    save: 'Salva',
    download: 'Scarica',
    share: 'Condividi',
    voice: 'Voce',
    stop: 'Ferma',
    copied: 'Copiato!',
    saved: 'Salvato!',
    downloaded: 'Scaricato!',
    
    // Generator page
    createContextAware: 'Crea scuse credibili e consapevoli del contesto con assistenza AI',
    configureContext: 'Configura Contesto',
    situation: 'Situazione',
    generatedExcuse: 'Scusa Generata',
    generating: 'Generando...',
    readyToGenerate: 'Pronto a Generare',
    configureContextAndGenerate: 'Configura il tuo contesto e clicca genera per creare la tua scusa',
    
    // Share modal
    checkOutExcuse: 'Guarda questa scusa',
    shareLinkCopied: 'Link di condivisione copiato negli appunti!',
    textCopiedInstagram: 'Testo copiato! Incollalo nel tuo post Instagram.',
    copyLink: 'Copia Link',
    believability: 'Credibilità',
    
    // Voice
    voiceNotSupported: 'Il text-to-speech non è supportato nel tuo browser.',
    
    // Download content
    excuseDocument: 'DOCUMENTO SCUSA',
    generated: 'Generato',
    generatedBy: 'Generato da',
    forPersonalUse: 'Questo contenuto è solo per uso personale.',
    
    // Context enhancement
    urgent: 'URGENTE',
    requiresImmediateAttention: 'Questo richiede attenzione immediata',
    quiteSerious: 'Questo è abbastanza serio e non può essere ritardato',
    sincerelyApologize: 'Mi scuso sinceramente per qualsiasi inconveniente questo possa causare',
    reallySorry: 'Mi dispiace davvero per questo, so che non è il momento ideale'
  },
  pt: {
    // Navigation
    dashboard: 'Painel',
    generateExcuse: 'Gerar Desculpa',
    proofGenerator: 'Gerador de Provas',
    emergencyAlerts: 'Alertas de Emergência',
    apologyGenerator: 'Gerador de Desculpas',
    settings: 'Configurações',
    savedExcuses: 'Desculpas Salvas',
    
    // Common terms
    believabilityScore: 'Pontuação de Credibilidade',
    category: 'Categoria',
    urgency: 'Urgência',
    audience: 'Audiência',
    relationship: 'Relacionamento',
    generateNow: 'Gerar Agora',
    saveExcuse: 'Salvar Desculpa',
    copyToClipboard: 'Copiar para Área de Transferência',
    shareExcuse: 'Compartilhar Desculpa',
    customizeProof: 'Personalizar Prova',
    scheduleAlert: 'Agendar Alerta',
    voicePlayback: 'Reprodução de Voz',
    
    // Categories
    work: 'Trabalho',
    medical: 'Médico',
    family: 'Família',
    transport: 'Transporte',
    technology: 'Tecnologia',
    weather: 'Clima',
    emergency: 'Emergência',
    personal: 'Pessoal',
    
    // Urgency levels
    low: 'Baixo',
    medium: 'Médio',
    high: 'Alto',
    critical: 'Crítico',
    
    // Audience types
    workProfessional: 'Trabalho/Profissional',
    friends: 'Amigos',
    romanticPartner: 'Parceiro Romântico',
    authorityFigure: 'Figura de Autoridade',
    
    // Relationship types
    close: 'Próximo',
    professional: 'Profissional',
    casual: 'Casual',
    distant: 'Distante',
    
    // Actions
    copy: 'Copiar',
    save: 'Salvar',
    download: 'Baixar',
    share: 'Compartilhar',
    voice: 'Voz',
    stop: 'Parar',
    copied: 'Copiado!',
    saved: 'Salvo!',
    downloaded: 'Baixado!',
    
    // Generator page
    createContextAware: 'Crie desculpas credíveis e conscientes do contexto com assistência de IA',
    configureContext: 'Configurar Contexto',
    situation: 'Situação',
    generatedExcuse: 'Desculpa Gerada',
    generating: 'Gerando...',
    readyToGenerate: 'Pronto para Gerar',
    configureContextAndGenerate: 'Configure seu contexto e clique em gerar para criar sua desculpa',
    
    // Share modal
    checkOutExcuse: 'Confira esta desculpa',
    shareLinkCopied: 'Link de compartilhamento copiado para a área de transferência!',
    textCopiedInstagram: 'Texto copiado! Cole em seu post do Instagram.',
    copyLink: 'Copiar Link',
    believability: 'Credibilidade',
    
    // Voice
    voiceNotSupported: 'Text-to-speech não é suportado em seu navegador.',
    
    // Download content
    excuseDocument: 'DOCUMENTO DE DESCULPA',
    generated: 'Gerado',
    generatedBy: 'Gerado por',
    forPersonalUse: 'Este conteúdo é apenas para uso pessoal.',
    
    // Context enhancement
    urgent: 'URGENTE',
    requiresImmediateAttention: 'Isso requer atenção imediata',
    quiteSerious: 'Isso é bastante sério e não pode ser adiado',
    sincerelyApologize: 'Peço sinceras desculpas por qualquer inconveniente que isso possa causar',
    reallySorry: 'Sinto muito por isso, sei que não é o momento ideal'
  },
  ru: {
    // Navigation
    dashboard: 'Панель управления',
    generateExcuse: 'Создать оправдание',
    proofGenerator: 'Генератор доказательств',
    emergencyAlerts: 'Экстренные уведомления',
    apologyGenerator: 'Генератор извинений',
    settings: 'Настройки',
    savedExcuses: 'Сохранённые оправдания',
    
    // Common terms
    believabilityScore: 'Оценка правдоподобности',
    category: 'Категория',
    urgency: 'Срочность',
    audience: 'Аудитория',
    relationship: 'Отношения',
    generateNow: 'Создать сейчас',
    saveExcuse: 'Сохранить оправдание',
    copyToClipboard: 'Скопировать в буфер',
    shareExcuse: 'Поделиться оправданием',
    customizeProof: 'Настроить доказательство',
    scheduleAlert: 'Запланировать уведомление',
    voicePlayback: 'Голосовое воспроизведение',
    
    // Categories
    work: 'Работа',
    medical: 'Медицинское',
    family: 'Семья',
    transport: 'Транспорт',
    technology: 'Технологии',
    weather: 'Погода',
    emergency: 'Экстренная ситуация',
    personal: 'Личное',
    
    // Urgency levels
    low: 'Низкая',
    medium: 'Средняя',
    high: 'Высокая',
    critical: 'Критическая',
    
    // Audience types
    workProfessional: 'Работа/Профессиональное',
    friends: 'Друзья',
    romanticPartner: 'Романтический партнёр',
    authorityFigure: 'Авторитетная фигура',
    
    // Relationship types
    close: 'Близкие',
    professional: 'Профессиональные',
    casual: 'Обычные',
    distant: 'Дистанционные',
    
    // Actions
    copy: 'Копировать',
    save: 'Сохранить',
    download: 'Скачать',
    share: 'Поделиться',
    voice: 'Голос',
    stop: 'Остановить',
    copied: 'Скопировано!',
    saved: 'Сохранено!',
    downloaded: 'Скачано!',
    
    // Generator page
    createContextAware: 'Создавайте правдоподобные оправдания с учётом контекста при помощи ИИ',
    configureContext: 'Настроить контекст',
    situation: 'Ситуация',
    generatedExcuse: 'Созданное оправдание',
    generating: 'Создание...',
    readyToGenerate: 'Готов к созданию',
    configureContextAndGenerate: 'Настройте контекст и нажмите создать для генерации оправдания',
    
    // Share modal
    checkOutExcuse: 'Посмотрите на это оправдание',
    shareLinkCopied: 'Ссылка для обмена скопирована в буфер!',
    textCopiedInstagram: 'Текст скопирован! Вставьте его в свой пост в Instagram.',
    copyLink: 'Копировать ссылку',
    believability: 'Правдоподобность',
    
    // Voice
    voiceNotSupported: 'Синтез речи не поддерживается в вашем браузере.',
    
    // Download content
    excuseDocument: 'ДОКУМЕНТ ОПРАВДАНИЯ',
    generated: 'Создано',
    generatedBy: 'Создано',
    forPersonalUse: 'Этот контент предназначен только для личного использования.',
    
    // Context enhancement
    urgent: 'СРОЧНО',
    requiresImmediateAttention: 'Это требует немедленного внимания',
    quiteSerious: 'Это довольно серьёзно и не может быть отложено',
    sincerelyApologize: 'Я искренне извиняюсь за любые неудобства, которые это может причинить',
    reallySorry: 'Мне действительно жаль, я знаю, что это не идеальное время'
  },
  ja: {
    // Navigation
    dashboard: 'ダッシュボード',
    generateExcuse: '言い訳を生成',
    proofGenerator: '証拠ジェネレーター',
    emergencyAlerts: '緊急アラート',
    apologyGenerator: '謝罪ジェネレーター',
    settings: '設定',
    savedExcuses: '保存された言い訳',
    
    // Common terms
    believabilityScore: '信憑性スコア',
    category: 'カテゴリー',
    urgency: '緊急度',
    audience: '対象者',
    relationship: '関係',
    generateNow: '今すぐ生成',
    saveExcuse: '言い訳を保存',
    copyToClipboard: 'クリップボードにコピー',
    shareExcuse: '言い訳を共有',
    customizeProof: '証拠をカスタマイズ',
    scheduleAlert: 'アラートをスケジュール',
    voicePlayback: '音声再生',
    
    // Categories
    work: '仕事',
    medical: '医療',
    family: '家族',
    transport: '交通',
    technology: 'テクノロジー',
    weather: '天気',
    emergency: '緊急事態',
    personal: '個人的',
    
    // Urgency levels
    low: '低',
    medium: '中',
    high: '高',
    critical: '重要',
    
    // Audience types
    workProfessional: '仕事/プロフェッショナル',
    friends: '友達',
    romanticPartner: 'ロマンチックパートナー',
    authorityFigure: '権威者',
    
    // Relationship types
    close: '親しい',
    professional: 'プロフェッショナル',
    casual: 'カジュアル',
    distant: '遠い',
    
    // Actions
    copy: 'コピー',
    save: '保存',
    download: 'ダウンロード',
    share: '共有',
    voice: '音声',
    stop: '停止',
    copied: 'コピーしました！',
    saved: '保存しました！',
    downloaded: 'ダウンロードしました！',
    
    // Generator page
    createContextAware: 'AIアシスタンスでコンテキストを意識した信頼できる言い訳を作成',
    configureContext: 'コンテキストを設定',
    situation: '状況',
    generatedExcuse: '生成された言い訳',
    generating: '生成中...',
    readyToGenerate: '生成準備完了',
    configureContextAndGenerate: 'コンテキストを設定して生成をクリックして言い訳を作成',
    
    // Share modal
    checkOutExcuse: 'この言い訳をチェック',
    shareLinkCopied: '共有リンクをクリップボードにコピーしました！',
    textCopiedInstagram: 'テキストをコピーしました！Instagramの投稿に貼り付けてください。',
    copyLink: 'リンクをコピー',
    believability: '信憑性',
    
    // Voice
    voiceNotSupported: 'お使いのブラウザではテキスト読み上げがサポートされていません。',
    
    // Download content
    excuseDocument: '言い訳ドキュメント',
    generated: '生成日時',
    generatedBy: '生成者',
    forPersonalUse: 'このコンテンツは個人使用のみです。',
    
    // Context enhancement
    urgent: '緊急',
    requiresImmediateAttention: 'これは即座の注意が必要です',
    quiteSerious: 'これはかなり深刻で遅らせることはできません',
    sincerelyApologize: 'これによってご迷惑をおかけすることを心よりお詫び申し上げます',
    reallySorry: 'これについて本当に申し訳ありません、理想的なタイミングではないことは分かっています'
  },
  ko: {
    // Navigation
    dashboard: '대시보드',
    generateExcuse: '변명 생성',
    proofGenerator: '증거 생성기',
    emergencyAlerts: '긴급 알림',
    apologyGenerator: '사과 생성기',
    settings: '설정',
    savedExcuses: '저장된 변명',
    
    // Common terms
    believabilityScore: '신뢰도 점수',
    category: '카테고리',
    urgency: '긴급도',
    audience: '대상',
    relationship: '관계',
    generateNow: '지금 생성',
    saveExcuse: '변명 저장',
    copyToClipboard: '클립보드에 복사',
    shareExcuse: '변명 공유',
    customizeProof: '증거 사용자 정의',
    scheduleAlert: '알림 예약',
    voicePlayback: '음성 재생',
    
    // Categories
    work: '업무',
    medical: '의료',
    family: '가족',
    transport: '교통',
    technology: '기술',
    weather: '날씨',
    emergency: '응급상황',
    personal: '개인',
    
    // Urgency levels
    low: '낮음',
    medium: '보통',
    high: '높음',
    critical: '중요',
    
    // Audience types
    workProfessional: '업무/전문적',
    friends: '친구들',
    romanticPartner: '연인',
    authorityFigure: '권위자',
    
    // Relationship types
    close: '가까운',
    professional: '전문적',
    casual: '일반적',
    distant: '먼',
    
    // Actions
    copy: '복사',
    save: '저장',
    download: '다운로드',
    share: '공유',
    voice: '음성',
    stop: '정지',
    copied: '복사됨!',
    saved: '저장됨!',
    downloaded: '다운로드됨!',
    
    // Generator page
    createContextAware: 'AI 지원으로 상황을 고려한 믿을 만한 변명 생성',
    configureContext: '상황 설정',
    situation: '상황',
    generatedExcuse: '생성된 변명',
    generating: '생성 중...',
    readyToGenerate: '생성 준비 완료',
    configureContextAndGenerate: '상황을 설정하고 생성을 클릭하여 변명을 만드세요',
    
    // Share modal
    checkOutExcuse: '이 변명을 확인하세요',
    shareLinkCopied: '공유 링크가 클립보드에 복사되었습니다!',
    textCopiedInstagram: '텍스트가 복사되었습니다! Instagram 게시물에 붙여넣으세요.',
    copyLink: '링크 복사',
    believability: '신뢰도',
    
    // Voice
    voiceNotSupported: '브라우저에서 텍스트 음성 변환을 지원하지 않습니다.',
    
    // Download content
    excuseDocument: '변명 문서',
    generated: '생성됨',
    generatedBy: '생성자',
    forPersonalUse: '이 콘텐츠는 개인 사용 전용입니다.',
    
    // Context enhancement
    urgent: '긴급',
    requiresImmediateAttention: '즉시 주의가 필요합니다',
    quiteSerious: '이것은 매우 심각하며 지연될 수 없습니다',
    sincerelyApologize: '이로 인해 발생할 수 있는 불편함에 대해 진심으로 사과드립니다',
    reallySorry: '정말 죄송합니다. 이상적인 타이밍이 아니라는 것을 알고 있습니다'
  },
  zh: {
    // Navigation
    dashboard: '仪表板',
    generateExcuse: '生成借口',
    proofGenerator: '证据生成器',
    emergencyAlerts: '紧急警报',
    apologyGenerator: '道歉生成器',
    settings: '设置',
    savedExcuses: '已保存的借口',
    
    // Common terms
    believabilityScore: '可信度评分',
    category: '类别',
    urgency: '紧急程度',
    audience: '受众',
    relationship: '关系',
    generateNow: '立即生成',
    saveExcuse: '保存借口',
    copyToClipboard: '复制到剪贴板',
    shareExcuse: '分享借口',
    customizeProof: '自定义证据',
    scheduleAlert: '安排警报',
    voicePlayback: '语音播放',
    
    // Categories
    work: '工作',
    medical: '医疗',
    family: '家庭',
    transport: '交通',
    technology: '技术',
    weather: '天气',
    emergency: '紧急情况',
    personal: '个人',
    
    // Urgency levels
    low: '低',
    medium: '中',
    high: '高',
    critical: '紧急',
    
    // Audience types
    workProfessional: '工作/专业',
    friends: '朋友',
    romanticPartner: '恋人',
    authorityFigure: '权威人士',
    
    // Relationship types
    close: '亲密',
    professional: '专业',
    casual: '随意',
    distant: '疏远',
    
    // Actions
    copy: '复制',
    save: '保存',
    download: '下载',
    share: '分享',
    voice: '语音',
    stop: '停止',
    copied: '已复制！',
    saved: '已保存！',
    downloaded: '已下载！',
    
    // Generator page
    createContextAware: '使用AI辅助创建情境感知的可信借口',
    configureContext: '配置情境',
    situation: '情况',
    generatedExcuse: '生成的借口',
    generating: '生成中...',
    readyToGenerate: '准备生成',
    configureContextAndGenerate: '配置您的情境并点击生成来创建您的借口',
    
    // Share modal
    checkOutExcuse: '查看这个借口',
    shareLinkCopied: '分享链接已复制到剪贴板！',
    textCopiedInstagram: '文本已复制！粘贴到您的Instagram帖子中。',
    copyLink: '复制链接',
    believability: '可信度',
    
    // Voice
    voiceNotSupported: '您的浏览器不支持文本转语音。',
    
    // Download content
    excuseDocument: '借口文档',
    generated: '生成时间',
    generatedBy: '生成者',
    forPersonalUse: '此内容仅供个人使用。',
    
    // Context enhancement
    urgent: '紧急',
    requiresImmediateAttention: '这需要立即关注',
    quiteSerious: '这相当严重，不能延迟',
    sincerelyApologize: '对此可能造成的任何不便，我真诚地道歉',
    reallySorry: '对此我真的很抱歉，我知道这不是理想的时机'
  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    generateExcuse: 'إنشاء عذر',
    proofGenerator: 'مولد الأدلة',
    emergencyAlerts: 'تنبيهات الطوارئ',
    apologyGenerator: 'مولد الاعتذارات',
    settings: 'الإعدادات',
    savedExcuses: 'الأعذار المحفوظة',
    
    // Common terms
    believabilityScore: 'نقاط المصداقية',
    category: 'الفئة',
    urgency: 'الإلحاح',
    audience: 'الجمهور',
    relationship: 'العلاقة',
    generateNow: 'إنشاء الآن',
    saveExcuse: 'حفظ العذر',
    copyToClipboard: 'نسخ إلى الحافظة',
    shareExcuse: 'مشاركة العذر',
    customizeProof: 'تخصيص الدليل',
    scheduleAlert: 'جدولة التنبيه',
    voicePlayback: 'تشغيل الصوت',
    
    // Categories
    work: 'العمل',
    medical: 'طبي',
    family: 'العائلة',
    transport: 'النقل',
    technology: 'التكنولوجيا',
    weather: 'الطقس',
    emergency: 'طوارئ',
    personal: 'شخصي',
    
    // Urgency levels
    low: 'منخفض',
    medium: 'متوسط',
    high: 'عالي',
    critical: 'حرج',
    
    // Audience types
    workProfessional: 'العمل/المهني',
    friends: 'الأصدقاء',
    romanticPartner: 'الشريك العاطفي',
    authorityFigure: 'شخصية السلطة',
    
    // Relationship types
    close: 'قريب',
    professional: 'مهني',
    casual: 'عادي',
    distant: 'بعيد',
    
    // Actions
    copy: 'نسخ',
    save: 'حفظ',
    download: 'تحميل',
    share: 'مشاركة',
    voice: 'صوت',
    stop: 'إيقاف',
    copied: 'تم النسخ!',
    saved: 'تم الحفظ!',
    downloaded: 'تم التحميل!',
    
    // Generator page
    createContextAware: 'إنشاء أعذار موثوقة ومدركة للسياق بمساعدة الذكاء الاصطناعي',
    configureContext: 'تكوين السياق',
    situation: 'الموقف',
    generatedExcuse: 'العذر المُنشأ',
    generating: 'جاري الإنشاء...',
    readyToGenerate: 'جاهز للإنشاء',
    configureContextAndGenerate: 'قم بتكوين السياق الخاص بك وانقر على إنشاء لإنتاج عذرك',
    
    // Share modal
    checkOutExcuse: 'تحقق من هذا العذر',
    shareLinkCopied: 'تم نسخ رابط المشاركة إلى الحافظة!',
    textCopiedInstagram: 'تم نسخ النص! الصقه في منشورك على Instagram.',
    copyLink: 'نسخ الرابط',
    believability: 'المصداقية',
    
    // Voice
    voiceNotSupported: 'تحويل النص إلى كلام غير مدعوم في متصفحك.',
    
    // Download content
    excuseDocument: 'وثيقة العذر',
    generated: 'تم الإنشاء',
    generatedBy: 'أنشأ بواسطة',
    forPersonalUse: 'هذا المحتوى للاستخدام الشخصي فقط.',
    
    // Context enhancement
    urgent: 'عاجل',
    requiresImmediateAttention: 'هذا يتطلب اهتماماً فورياً',
    quiteSerious: 'هذا خطير جداً ولا يمكن تأجيله',
    sincerelyApologize: 'أعتذر بصدق عن أي إزعاج قد يسببه هذا',
    reallySorry: 'أنا آسف حقاً لهذا، أعلم أنه ليس التوقيت المثالي'
  }
};

export function useTranslation(language: string) {
  const t = (key: keyof typeof translations.en): string => {
    const lang = language as keyof typeof translations;
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return { t };
}